vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute
        
    mappings:
       images_sinister:
           uri_prefix: /upload/sinister
           upload_destination: '%kernel.project_dir%/public/images/sinister'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
